### ISSUE TITLE
File local_image_provider-Swift.h missing

### ISSUE THREAD

**Issue by jbureau17** [csdcorp/local_image_provider#14]
Hi I am trying to use this plugin on macOS but it seems to be missing a file.
```
Launching lib/main.dart on iPad Air (3rd generation) in debug mode...
Running Xcode build...
Xcode build done.                                            1.7s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/username/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/local_image_provider-0.6.0/ios/Classes/LocalImageProviderPlugin.m:2:9: fatal error: 'local_image_provider/local_image_provider-Swift.h' file not found
    #import <local_image_provider/local_image_provider-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build systemnote: Planning buildnote: Constructing build description

Could not build the application for the simulator.
Error launching application on iPad Air (3rd generation).

```

**Comment by sowens-csd** [comment]
Sorry to hear you're having trouble with it. Can you give me your Flutter version information so I can troubleshoot? Flutter doctor output would be fine. 

It is true that file is not there, but it's not causing any problems for me. I think I saw something about mixed Objective-c and Swift plugins causing problems. I'll look into it.

**Comment by sowens-csd** [comment]
There's a longish thread here https://github.com/BaseflowIT/flutter-geolocator/issues/17 that looks like it explains both the issue and likely solutions. Let me know if you think it's relevant to your problem, if not I'll keep looking. It does appear to be related to some incompatibility between various plugin styles and the app. 

At the very least I should update the documentation to help others avoid the problem so anything you find out would be useful.

**Comment by jbureau17** [comment]
Thanks for the quick reply! I found a solution in that thread.
I have to add the following line to Podfile:
`use_frameworks!`

**Comment by sowens-csd** [comment]
Thanks for letting me know. I'll update the docs and close the issue once that's done.
