### ISSUE TITLE
ISSUE WITH LOADING VIDEOS

### ISSUE THREAD

**Issue by Mal2107** [csdcorp/local_image_provider#27]
When i call LocalImageProvider().findlatest() no video is returned in the list only images.
What am I doing wrong??

**Comment by sowens-csd** [comment]
Good question, I'll have to check and see if it should be. The plugin originally returned only images and I may not have changed that method to include video. Were you testing on iOS or Android? And which version?

**Comment by Mal2107** [comment]
I am using Android and using the latest version of the plugin

**Comment by sowens-csd** [comment]
Looks like no, that method does not select videos. It should, working on the change now.

**Comment by sowens-csd** [comment]
The latest version on the main branch in the repo has a fix for this issue. It will be released as 2.2.0 as soon as I get feedback on another fix that's included with the same version. If you'd like you can try it now from the repo.

**Comment by Mal2107** [comment]
Great thanks a lot
