### ISSUE TITLE
not working with Android Q

### ISSUE THREAD

**Issue by reachenbee** [csdcorp/local_image_provider#28]
I/flutter ( 6222): Instance of 'LocalImageProvider'
E/AndroidRuntime( 6222): FATAL EXCEPTION: Thread-5
E/AndroidRuntime( 6222): Process: com.offload.triggers, PID: 6222
E/AndroidRuntime( 6222): java.lang.IllegalArgumentException: Invalid column DISTINCT bucket_display_name
E/AndroidRuntime( 6222): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
E/AndroidRuntime( 6222): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
E/AndroidRuntime( 6222): 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
E/AndroidRuntime( 6222): 	at android.content.ContentResolver.query(ContentResolver.java:944)
E/AndroidRuntime( 6222): 	at android.content.ContentResolver.query(ContentResolver.java:880)
E/AndroidRuntime( 6222): 	at android.content.ContentResolver.query(ContentResolver.java:836)
E/AndroidRuntime( 6222): 	at com.csdcorp.local_image_provider.LocalImageProviderPlugin.getAlbumsFromLocation(LocalImageProviderPlugin.kt:293)
E/AndroidRuntime( 6222): 	at com.csdcorp.local_image_provider.LocalImageProviderPlugin.access$getAlbumsFromLocation(LocalImageProviderPlugin.kt:50)
E/AndroidRuntime( 6222): 	at com.csdcorp.local_image_provider.LocalImageProviderPlugin$getAlbums$1.run(LocalImageProviderPlugin.kt:249)
E/AndroidRuntime( 6222): 	at java.lang.Thread.run(Thread.java:919)
I/Process ( 6222): Sending signal. PID: 6222 SIG: 9

**Comment by reachenbee** [comment]
do we have any fix for this please ?
https://stackoverflow.com/questions/58601599/illegalargumentexception-invalid-column-distinct-bucket-display-name

**Comment by sowens-csd** [comment]
Thanks for submitting the issue. Looks like a pretty major change in the way SQL works in Android Q. Working on a fix for this behaviour now.

**Comment by sowens-csd** [comment]
There's a fix for this on the main branch now. Could you give it a try? I've tried it on an emulator and it's fine but I don't have a Q device around so I'd like to check the result on a real device before I release.

**Comment by reachenbee** [comment]
ok, sure, i'll give it a try and will let you know. Thanks much for the quick response, appreciate.

**Comment by reachenbee** [comment]
I got the blow error this time.


E/AndroidRuntime( 8112): FATAL EXCEPTION: Thread-4
E/AndroidRuntime( 8112): Process: com.offload.triggers, PID: 8112
E/AndroidRuntime( 8112): java.lang.IllegalArgumentException: Invalid token LIMIT
E/AndroidRuntime( 8112): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
E/AndroidRuntime( 8112): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
E/AndroidRuntime( 8112): 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:472)
E/AndroidRuntime( 8112): 	at android.content.ContentResolver.query(ContentResolver.java:1183)
E/AndroidRuntime( 8112): 	at android.content.ContentResolver.query(ContentResolver.java:1115)
E/AndroidRuntime( 8112): 	at android.content.ContentResolver.query(ContentResolver.java:1071)
E/AndroidRuntime( 8112): 	at com.csdcorp.local_image_provider.LocalImageProviderPlugin.findImagesToMedia(LocalImageProviderPlugin.kt:504)
E/AndroidRuntime( 8112): 	at com.csdcorp.local_image_provider.LocalImageProviderPlugin.access$findImagesToMedia(LocalImageProviderPlugin.kt:77)
E/AndroidRuntime( 8112): 	at com.csdcorp.local_image_provider.LocalImageProviderPlugin$getLatestImages$1.run(LocalImageProviderPlugin.kt:441)
E/AndroidRuntime( 8112): 	at java.lang.Thread.run(Thread.java:923)
I/Process ( 8112): Sending signal. PID: 8112 SIG: 9

**Comment by reachenbee** [comment]
this is the AVD I am using to check. The DISTINCT error is not appearing now.

<img width="1004" alt="Screenshot 2020-09-19 at 11 36 06 AM" src="https://user-images.githubusercontent.com/6803940/93660426-62d8aa80-fa6c-11ea-8fdf-71de5f93ccc4.png">

**Comment by sowens-csd** [comment]
Thanks for trying it. Looks like the change to remove the LIMIT was after the change to remove the DISTINCT so I didn't catch it. 

Unfortunately I'm having problems getting an Android 11 simulator running so I still can't effectively test this. I'll troubleshoot that but in the meantime there's a new version in the repo that should now work.

**Comment by reachenbee** [comment]
Thanks much, I tried the new version and it works.

**Comment by sowens-csd** [comment]
Thanks a lot for the help. 2.2.0 is now live on pub.dev. 
Also an emulator update fixed my issue with starting an 11 emulator so I can test with that going forward.
