### ISSUE TITLE
Photo images are downsized on iOS due to swapping of width and height

### ISSUE THREAD

**Issue by flora-gr** [csdcorp/local_image_provider#29]
A fix is hosted in this branch: https://github.com/flora-gr/local_image_provider_dimensions_swap_fix

**Comment by sowens-csd** [comment]
Great find, thank you! Do you want to create a PR for it or would you rather I just make the change?

**Comment by flora-gr** [comment]
I'll create a PR :)

**Comment by sowens-csd** [comment]
Thanks for the help! I merged the PR and have released this as 2.2.1.
