### ISSUE TITLE
Adding jpeg compression as an optional parameter

### ISSUE THREAD

**Issue by flora-gr** [csdcorp/local_image_provider#31]
We would like to have more control over image compression within this plugin. Is this something you would consider implementing? A possible implementation is shown in the branch below.

https://github.com/flora-gr/local_image_provider/tree/feature/compression-as-optional-parameter

**Comment by sowens-csd** [comment]
Yes, sounds like a good improvement to me. If we're going to add it though it should probably be available wherever images are retrieved. I think the other locations are:

- DeviceImage, the compression could be added as an optional named parameter to the DeviceImage constructor and then passed through to the imageBytes call.
- LocalImage, same thing
- LocalAlbum.getCoverImage

What do you think?

**Comment by flora-gr** [comment]
Sure, that makes sense. I'll have a go at it.

**Comment by sowens-csd** [comment]
I just merged your PR, thank you. I'll test it on Android and iOS and then release as version 2.3.0.

**Comment by sowens-csd** [comment]
This is now released as 2.3.0
