### ISSUE TITLE
Getting image path / bytestring of LocalImage

### ISSUE THREAD

**Issue by carlblock** [csdcorp/local_image_provider#33]
This is more a general question about the `LocalImage` class.

Is there anyway to get the file path from the image or read it as a byte stream? The reason why I'm interested in this is for being able to upload these images.

Thanks!

**Comment by carlblock** [comment]
I'll answer my own question here, I looked inside the `LocalImageProvider` class and found a method.

```dart
LocalImageProvider localImageProvider = LocalImageProvider();
await localImageProvider.imageBytes(myImage.id, 1080, 1080);
```

Sorry for bothering in these issues. And thanks for a lovely library!

**Comment by AryashDubey** [comment]
Thank you, had raised the question myself. Your solution works for me! Gonna close the issue with a nice apology haha!

**Comment by AryashDubey** [comment]
Hey, Carl if you are reading this can you help me out with a way to upload the file on the server? Please that will help me a lot!
