### ISSUE TITLE
iOS 14 PHPhotoLibrary Limited Authorization Status

### ISSUE THREAD

**Issue by wpfilf** [csdcorp/local_image_provider#36]
Dear developers from csdcorp, thx for this awesome flutter plugin. I have a question regarding iOS 14+'s permission feature of limiting access to selected photos: PHAuthorizationStatus.limited

https://developer.apple.com/documentation/photokit/phauthorizationstatus

Each time LocalImageProvider is initializing there's an iOS permission dialog showing, asking the user to select additional photos. 
Is there a way to support iOS's limited photo permissions and initializing LocalImageProver without showing the permission dialog?

**Comment by sowens-csd** [comment]
Great question, yes, there should be. I'll have a look at how to support it, thanks for the feedback.

**Comment by sowens-csd** [comment]
The latest commit in the repo should now properly support this. If you have a chance give it a try. I also added a note to the README about the new info.plist property `PHPhotoLibraryPreventAutomaticLimitedAccessAlert` which can be set to block this dialog. This will be released as 2.3.0.

**Comment by sowens-csd** [comment]
This is now available in 2.3.0
