### ISSUE TITLE
`lip.LocalImage` isn't exposed publicly

### ISSUE THREAD

**Issue by agordeev** [csdcorp/local_image_provider#39]
The same issue is described here: 

https://github.com/csdcorp/local_image_provider/issues/35

In the current version, `LocalImage` is visible only internally to the library. It's not exposed outside.

A workaround is to import `LocalImage`:

```
import 'package:local_image_provider/local_image.dart' as lip;
import 'package:local_image_provider/local_image_provider.dart' as lip;
```

**Comment by sowens-csd** [comment]
This is resolved, after too long a wait, in 4.1.0 which is on pub.dev now.
