### ISSUE TITLE
GeneratedAppGlideModuleImpl is implemented incorrectly.

### ISSUE THREAD

**Issue by dungnc** [csdcorp/local_image_provider#42]
I'm using version 4.0.1 and I got this issue when I was trying to get image path.

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(imgLoadFailed, Exception while loading image, GeneratedAppGlideModuleImpl is implemented incorrectly. If you've manually implemented this class, remove your implementation. The Annotation processor will generate a correct implementation., null)

This is How I get Image Path.
```
var fileByte = await lip.LocalImageProvider().imageBytes(li.id!, li.pixelHeight!, li.pixelWidth!);
file = await file.writeAsBytes(fileByte);
```

**Comment by sowens-csd** [comment]
I just tried this in 4.0.2 and it seems to be working properly. However this could be a problem with a specific OS or Flutter version so if this issue is still relevant for you let me know where you saw it. I realize this is a bit old so this may no longer be relevant.

**Comment by flora-gr** [comment]
Hi, I see that you closed this issue but we now also experience this problem. For us, it occurs when using firebase_in_app_messaging (which also uses AppGlideModule) in combination with local_image_provider. When we launch our app for Android, we get the above error and the app crashes. We would really appreciate it if you can have a look at this!
